[package]
name = "alarm-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.208"
serde_derive = "1.0.208"
toml = "0.8.19"
serde_json = "1.0.125"
flume = "0.11.0"
imap = "3.0.0-alpha.14"
mailparse = "0.15.0"
mail-parser = "0.9.4"
regex = "1.10.6"
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.21.0"
quoted_printable = "0.5.1"
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
urlencoding = "2.1.3"
async-trait = "0.1.83"
twox-hash = "2.1.0"
